### ISSUE TITLE
missing: API_KEY_FOR_ANDROID

### ISSUE THREAD

**Issue by AhmadEl-Banna** [thebakeryio/meteor-cordova-native-map#1]
Hi I'm new to Meteor a Ihve follow the instructions provided of you blog post http://thebakery.io/blog/native-ios-maps-with-meteor-and-cordova/

and I have add 
App.configurePlugin('plugin.google.maps', {
    'API_KEY_FOR_IOS': 'my-key',
    'API_KEY_FOR_ANDROID':"key"
});

but it filaed to build on android with this error 
Error: Variable(s) missing: API_KEY_FOR_ANDROID

did I did any thing wrong ?

**Comment by callmephilip** [comment]
Hey Ahmad, 

We've only tested this with iOS so current instructions do NOT really work for Android. We'll try to add Android support in the future. Sorry about that.

**Comment by AhmadEl-Banna** [comment]
thanks  callmephilip , 
It's working now for android , it was my fault  I write the plugin configration code in config.js while I should name the file as mobile-config.js 
thanks for paying attention

**Comment by callmephilip** [comment]
@AhmadEl-Banna: Ahmad, did you manage to run the map on an actual Android device? Would be curions to know how the experience is
